version: "3"
services:
  nginx_static_server:
    build: ./nginx-static-server
    environment:
      ADDITIONAL_NGINX_CONFIG: |
        location /foo {
          return 301 $scheme://$http_host/app$is_args$args;
        }
    ports:
      - 8080:80
    volumes:
      - ./nginx-static-server/test/index.html:/usr/share/nginx/html/index.html
