version: "3"
services:
  nginx_static_server:
    build: ./nginx-static-server
    environment:
      ADDITIONAL_NGINX_CONFIG: "
        location /foo {
        return 301 $$scheme://$$http_host/app$$is_args$$args;
        }"
      DEPLOY_ENVIRONMENT: production
    ports:
      - 8080:80
    volumes:
      - ./nginx-static-server/test/static:/app/dist/production
      - ./nginx-static-server/test/redirects.conf:/etc/nginx/conf.d/includes/redirects.conf
